const $=s=>document.querySelector(s), photo=$('#photo'), canvas=$('#preview'), ctx=canvas.getContext('2d',{willReadFrequently:true});let original=null;
const storeKey='meter-readings-v1';
photo.onchange=async()=>{const f=photo.files[0];if(!f)return;original=await createImageBitmap(f);const max=1800,scale=Math.min(1,max/original.width);canvas.width=Math.round(original.width*scale);canvas.height=Math.round(original.height*scale);ctx.drawImage(original,0,0,canvas.width,canvas.height);canvas.style.display='block';$('#analyze').disabled=false;$('#progress').textContent='Immagine pronta.'};
function processedCanvas(){const c=document.createElement('canvas'),w=canvas.width,h=canvas.height;c.width=w;c.height=h;const x=c.getContext('2d');x.drawImage(canvas,0,0);const im=x.getImageData(0,0,w,h),d=im.data;let sum=0;for(let i=0;i<d.length;i+=4)sum+=(d[i]*.299+d[i+1]*.587+d[i+2]*.114);const mean=sum/(d.length/4);for(let i=0;i<d.length;i+=4){let g=d[i]*.299+d[i+1]*.587+d[i+2]*.114;g=(g-mean)*1.7+128;g=Math.max(0,Math.min(255,g));d[i]=d[i+1]=d[i+2]=g}x.putImageData(im,0,0);return c}
function parseOCR(text){const lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean);const nums=[...text.matchAll(/\b\d[\d .,'’]{2,}\d\b/g)].map(m=>m[0].replace(/\s/g,'')).map(s=>({raw:s,val:s.replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.').replace(/[^0-9.]/g,'')})).filter(x=>/^\d+(?:\.\d+)?$/.test(x.val));const reading=nums.sort((a,b)=>b.val.length-a.val.length)[0]?.val||'';const codeLines=lines.filter(l=>/[A-Z]/i.test(l)&&/\d/.test(l)&&l.length>=4&&l.length<=32);const code=(codeLines.find(l=>/serial|matric|cod|meter|contat/i.test(l))||codeLines[0]||'').replace(/^(serial|matricola|codice|meter|contatore)\s*[:#-]?\s*/i,'').trim();return{reading,code}}
$('#analyze').onclick=async()=>{if(!original)return;$('#analyze').disabled=true;$('#progress').textContent='OCR in corso…';try{const result=await Tesseract.recognize(processedCanvas(),'eng',{logger:m=>{if(m.status==='recognizing text')$('#progress').textContent=`Riconoscimento ${Math.round((m.progress||0)*100)}%`}});const text=result.data.text||'';$('#raw').textContent=text;const p=parseOCR(text);$('#meterCode').value=p.code;$('#reading').value=p.reading;$('#progress').textContent=`Completato. Confidenza OCR: ${Math.round(result.data.confidence||0)}%. Verifica i due campi prima di salvare.`}catch(e){$('#progress').textContent='Errore OCR: '+e.message}finally{$('#analyze').disabled=false}};
function load(){return JSON.parse(localStorage.getItem(storeKey)||'[]')}function persist(x){localStorage.setItem(storeKey,JSON.stringify(x));render()}
$('#save').onclick=()=>{const code=$('#meterCode').value.trim(),r=$('#reading').value.trim().replace(',','.');if(!code||!/^\d+(?:\.\d+)?$/.test(r)){alert('Controlla codice contatore e lettura kWh.');return}const a=load();a.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),code,reading:r,notes:$('#notes').value.trim()});persist(a);$('#progress').textContent='Lettura salvata sul dispositivo.'};
$('#clear').onclick=()=>{$('#meterCode').value=$('#reading').value=$('#notes').value=$('#raw').textContent='';$('#progress').textContent=''};
function render(){const a=load();$('#history').innerHTML=a.map(x=>`<tr><td>${new Date(x.date).toLocaleString('it-IT')}</td><td>${esc(x.code)}</td><td>${esc(x.reading)}</td><td>${esc(x.notes)}</td><td><button class="secondary" data-del="${x.id}">×</button></td></tr>`).join('')||'<tr><td colspan="5">Nessuna lettura</td></tr>';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>persist(load().filter(x=>x.id!==b.dataset.del)))}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#csv').onclick=()=>{const a=load();if(!a.length)return alert('Nessun dato da esportare.');const rows=[['Data','Codice contatore','Lettura kWh','Note'],...a.map(x=>[new Date(x.date).toLocaleString('it-IT'),x.code,x.reading,x.notes])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');const u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),ael=document.createElement('a');ael.href=u;ael.download='letture_contatori.csv';ael.click();URL.revokeObjectURL(u)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();