const $=s=>document.querySelector(s),canvas=$('#preview'),ctx=canvas.getContext('2d',{willReadFrequently:true});let original=null;
const storeKey='meter-readings-v1';
const METERS=[
 {code:'QL7/1',aliases:['QL7/1'],family:'IME NEMO 144'}, {code:'QL7/3',aliases:['QL7/3'],family:'IME NEMO 144'}, {code:'QK7/3',aliases:['QK7/3'],family:'IME NEMO 144'},
 {code:'QCAP1',aliases:['QCAP1','QCPA1','COMP1','COMP.1','COMP 1'],family:'Electrex VIPD3'}, {code:'QCAP2',aliases:['QCAP2','QCPA2','COMP2','COMP.2','COMP 2'],family:'Electrex VIPD3'},
 {code:'QCAP5',aliases:['QCAP5','QCPA5','COMP5','COMP.5','COMP 5'],family:'IME CONTO D4-Pt'}, {code:'QCAP3',aliases:['QCAP3','QCPA3','COMP3','COMP.3','COMP 3'],family:'IME NEMO D4-Le'},
 {code:'QCAP4',aliases:['QCAP4','QCPA4','COMP4','COMP.4','COMP 4'],family:'IME CONTO D4-Pt'}, {code:'QKL13',aliases:['QKL13','QKL 13'],family:'IME NEMO D4-Le'}];
const byCode=c=>METERS.find(m=>m.code===c),norm=s=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
function identifyMeter(text){const n=norm(text);let best=null;for(const m of METERS)for(const a of m.aliases){const na=norm(a);if(na&&n.includes(na)&&(!best||na.length>best.len))best={meter:m,len:na.length}}return best?.meter||null}
async function loadPhoto(input){const f=input.files?.[0];if(!f)return;original=await createImageBitmap(f);const max=2200,scale=Math.min(1,max/original.width);canvas.width=Math.round(original.width*scale);canvas.height=Math.round(original.height*scale);ctx.drawImage(original,0,0,canvas.width,canvas.height);canvas.style.display='block';$('#analyze').disabled=false;$('#progress').textContent='Immagine pronta.'}
$('#cameraPhoto').onchange=e=>loadPhoto(e.target);$('#libraryPhoto').onchange=e=>loadPhoto(e.target);
function cropCanvas(top=.35,bottom=.95,left=.05,right=.95){const c=document.createElement('canvas'),sx=Math.round(canvas.width*left),sy=Math.round(canvas.height*top),sw=Math.round(canvas.width*(right-left)),sh=Math.round(canvas.height*(bottom-top));c.width=sw;c.height=sh;c.getContext('2d').drawImage(canvas,sx,sy,sw,sh,0,0,sw,sh);return c}
function enhance(src,mode=0){const c=document.createElement('canvas');c.width=src.width;c.height=src.height;const x=c.getContext('2d');x.drawImage(src,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data;let sum=0;for(let i=0;i<d.length;i+=4)sum+=d[i]*.299+d[i+1]*.587+d[i+2]*.114;const mean=sum/(d.length/4);for(let i=0;i<d.length;i+=4){let g=d[i]*.299+d[i+1]*.587+d[i+2]*.114;g=(g-mean)*(mode?2.6:1.9)+128;if(mode===2)g=g>128?255:0;g=Math.max(0,Math.min(255,g));d[i]=d[i+1]=d[i+2]=g}x.putImageData(im,0,0);return c}
function nums(text){return [...String(text).matchAll(/\d[\d\s.,'’]{2,}\d/g)].map(m=>{let s=m[0].replace(/[\s'’]/g,'');if(s.includes(',')&&s.includes('.')){const p=Math.max(s.lastIndexOf(','),s.lastIndexOf('.'));s=s.slice(0,p).replace(/[.,]/g,'')+'.'+s.slice(p+1)}else if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if((s.match(/\./g)||[]).length>1)s=s.replace(/\./g,'');s=s.replace(/[^0-9.]/g,'');return s}).filter(s=>/^\d+(?:\.\d+)?$/.test(s))}
function scoreReading(s){const digits=s.replace('.','');let n=digits.length>=5?30:0;if(digits.length>=6&&digits.length<=9)n+=25;if(s.includes('.'))n+=12;const v=Number(s);if(v>100&&v<1e9)n+=10;return n}
function pickReading(texts){const candidates=[];for(const text of texts){const lines=text.split(/\n/);for(const line of lines){for(const n of nums(line)){let score=scoreReading(n);if(/k\s*w\s*h/i.test(line))score+=70;if(/M\s*W\s*h/i.test(line))score+=45;if(/V|A|kW(?!h)/i.test(line))score-=20;candidates.push({n,score,line})}}}candidates.sort((a,b)=>b.score-a.score);return candidates[0]||null}
async function ocr(img,label,opts={}){const r=await Tesseract.recognize(img,'eng',{...opts,logger:m=>{if(m.status==='recognizing text')$('#progress').textContent=`${label}: ${Math.round((m.progress||0)*100)}%`}});return r.data}
$('#analyze').onclick=async()=>{if(!original)return;$('#analyze').disabled=true;$('#progress').textContent='Analisi V3…';try{const selected=byCode($('#knownMeter').value);const full=await ocr(enhance(canvas,0),'Identificazione contatore');const meter=selected||identifyMeter(full.text);const display=cropCanvas(.32,.93,.04,.96);const pass1=await ocr(enhance(display,1),'Lettura display 1',{tessedit_char_whitelist:'0123456789.,kWhMVA '});const pass2=await ocr(enhance(display,2),'Lettura display 2',{tessedit_char_whitelist:'0123456789.,kWhMVA '});const best=pickReading([pass1.text,pass2.text,full.text]);$('#meterCode').value=meter?.code||'';$('#reading').value=best?.n||'';$('#meterHint').textContent=meter?`Riconosciuto: ${meter.code} · ${meter.family}${selected?' (selezionato)':''}`:'Contatore non identificato: selezionalo dall’elenco o inserisci il codice.';$('#raw').textContent=`--- FOTO COMPLETA ---\n${full.text}\n--- DISPLAY PASS 1 ---\n${pass1.text}\n--- DISPLAY PASS 2 ---\n${pass2.text}\n--- SCELTA ---\n${best?best.n+' | '+best.line:'nessuna lettura affidabile'}`;$('#progress').textContent=best?'Analisi completata. Verifica la lettura prima di salvarla.':'Nessuna lettura affidabile: prova una foto più frontale o seleziona il contatore.'}catch(e){$('#progress').textContent='Errore OCR: '+e.message}finally{$('#analyze').disabled=false}};
function load(){return JSON.parse(localStorage.getItem(storeKey)||'[]')}function persist(x){localStorage.setItem(storeKey,JSON.stringify(x));render()}
$('#save').onclick=()=>{const code=$('#meterCode').value.trim().toUpperCase(),r=$('#reading').value.trim().replace(',','.');if(!code||!/^\d+(?:\.\d+)?$/.test(r)){alert('Controlla codice contatore e lettura kWh.');return}const a=load();a.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),code,reading:r,notes:$('#notes').value.trim()});persist(a);$('#progress').textContent='Lettura salvata sul dispositivo.'};
$('#clear').onclick=()=>{$('#meterCode').value=$('#reading').value=$('#notes').value=$('#raw').textContent=$('#meterHint').textContent='';$('#knownMeter').value='';$('#progress').textContent=''};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function render(){const a=load();$('#history').innerHTML=a.map(x=>`<tr><td>${new Date(x.date).toLocaleString('it-IT')}</td><td>${esc(x.code)}</td><td>${esc(x.reading)}</td><td>${esc(x.notes)}</td><td><button class="secondary" data-del="${x.id}">×</button></td></tr>`).join('')||'<tr><td colspan="5">Nessuna lettura</td></tr>';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>persist(load().filter(x=>x.id!==b.dataset.del)))}
$('#csv').onclick=()=>{const a=load();if(!a.length)return alert('Nessun dato da esportare.');const rows=[['Data','Codice contatore','Lettura kWh','Note'],...a.map(x=>[new Date(x.date).toLocaleString('it-IT'),x.code,x.reading,x.notes])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');const u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),ael=document.createElement('a');ael.href=u;ael.download='letture_contatori.csv';ael.click();URL.revokeObjectURL(u)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();