const $=s=>document.querySelector(s),canvas=$('#preview'),ctx=canvas.getContext('2d',{willReadFrequently:true});let original=null;
const storeKey='meter-readings-v1';
const METERS=[
 {code:'QL7/1',aliases:['QL7/1'],family:'IME NEMO 144'},
 {code:'QL7/3',aliases:['QL7/3'],family:'IME NEMO 144'},
 {code:'QK7/3',aliases:['QK7/3'],family:'IME NEMO 144'},
 {code:'QCAP1',aliases:['QCAP1','QCPA1','COMP1','COMP.1','COMP 1'],family:'Electrex VIPD3'},
 {code:'QCAP2',aliases:['QCAP2','QCPA2','COMP2','COMP.2','COMP 2'],family:'Electrex VIPD3'},
 {code:'QCAP5',aliases:['QCAP5','QCPA5','COMP5','COMP.5','COMP 5'],family:'IME CONTO D4-Pt'},
 {code:'QCAP3',aliases:['QCAP3','QCPA3','COMP3','COMP.3','COMP 3'],family:'IME NEMO D4-Le'},
 {code:'QCAP4',aliases:['QCAP4','QCPA4','COMP4','COMP.4','COMP 4'],family:'IME CONTO D4-Pt'},
 {code:'QKL13',aliases:['QKL13','QKL 13'],family:'IME NEMO D4-Le'}
];
function norm(s){return String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function identifyMeter(text){const n=norm(text);let best=null;for(const m of METERS)for(const a of m.aliases){const na=norm(a);if(na&&n.includes(na)&&(!best||na.length>best.len))best={meter:m,len:na.length}}return best?.meter||null}
async function loadPhoto(input){const f=input.files?.[0];if(!f)return;original=await createImageBitmap(f);const max=2000,scale=Math.min(1,max/original.width);canvas.width=Math.round(original.width*scale);canvas.height=Math.round(original.height*scale);ctx.drawImage(original,0,0,canvas.width,canvas.height);canvas.style.display='block';$('#analyze').disabled=false;$('#progress').textContent='Immagine pronta.'}
$('#cameraPhoto').onchange=e=>loadPhoto(e.target);$('#libraryPhoto').onchange=e=>loadPhoto(e.target);
function processedCanvas(){const c=document.createElement('canvas'),w=canvas.width,h=canvas.height;c.width=w;c.height=h;const x=c.getContext('2d');x.drawImage(canvas,0,0);const im=x.getImageData(0,0,w,h),d=im.data;let sum=0;for(let i=0;i<d.length;i+=4)sum+=(d[i]*.299+d[i+1]*.587+d[i+2]*.114);const mean=sum/(d.length/4);for(let i=0;i<d.length;i+=4){let g=d[i]*.299+d[i+1]*.587+d[i+2]*.114;g=(g-mean)*1.85+128;g=Math.max(0,Math.min(255,g));d[i]=d[i+1]=d[i+2]=g}x.putImageData(im,0,0);return c}
function numberCandidates(text){return [...text.matchAll(/\d[\d\s.,'’]{2,}\d/g)].map(m=>{const raw=m[0].trim();let s=raw.replace(/[\s'’]/g,'');if(s.includes(',')&&s.includes('.')){const last=Math.max(s.lastIndexOf(','),s.lastIndexOf('.'));s=s.slice(0,last).replace(/[.,]/g,'')+'.'+s.slice(last+1)}else if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');else if((s.match(/\./g)||[]).length>1)s=s.replace(/\./g,'');return{raw,val:s.replace(/[^0-9.]/g,''),index:m.index}}).filter(x=>/^\d+(?:\.\d+)?$/.test(x.val))}
function parseOCR(text){const meter=identifyMeter(text),lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean),nums=numberCandidates(text);let reading='';const kwhLine=lines.find(l=>/k\s*w\s*h/i.test(l)&&/\d/.test(l));if(kwhLine){const a=numberCandidates(kwhLine);reading=a.sort((x,y)=>y.val.replace('.','').length-x.val.replace('.','').length)[0]?.val||''}if(!reading){const k=text.search(/k\s*w\s*h/i);if(k>=0){reading=nums.slice().sort((a,b)=>Math.abs(a.index-k)-Math.abs(b.index-k))[0]?.val||''}}if(!reading)reading=nums.filter(x=>x.val.replace('.','').length>=5).sort((a,b)=>b.val.replace('.','').length-a.val.replace('.','').length)[0]?.val||'';let code=meter?.code||'';if(!code){const codeLines=lines.filter(l=>/[A-Z]/i.test(l)&&/\d/.test(l)&&l.length>=3&&l.length<=32);code=(codeLines.find(l=>/serial|matric|cod|meter|contat/i.test(l))||codeLines[0]||'').replace(/^(serial|matricola|codice|meter|contatore)\s*[:#-]?\s*/i,'').trim()}return{reading,code,meter}}
$('#analyze').onclick=async()=>{if(!original)return;$('#analyze').disabled=true;$('#progress').textContent='OCR in corso…';try{const result=await Tesseract.recognize(processedCanvas(),'eng',{logger:m=>{if(m.status==='recognizing text')$('#progress').textContent=`Riconoscimento ${Math.round((m.progress||0)*100)}%`}});const text=result.data.text||'';$('#raw').textContent=text;const p=parseOCR(text);$('#meterCode').value=p.code;$('#reading').value=p.reading;$('#meterHint').textContent=p.meter?`Riconosciuto: ${p.meter.code} · ${p.meter.family}`:'Contatore non identificato automaticamente: verifica il codice.';$('#progress').textContent=`Completato. Confidenza OCR: ${Math.round(result.data.confidence||0)}%. Verifica codice e kWh prima di salvare.`}catch(e){$('#progress').textContent='Errore OCR: '+e.message}finally{$('#analyze').disabled=false}};
function load(){return JSON.parse(localStorage.getItem(storeKey)||'[]')}function persist(x){localStorage.setItem(storeKey,JSON.stringify(x));render()}
$('#save').onclick=()=>{const code=$('#meterCode').value.trim().toUpperCase(),r=$('#reading').value.trim().replace(',','.');if(!code||!/^\d+(?:\.\d+)?$/.test(r)){alert('Controlla codice contatore e lettura kWh.');return}const a=load();a.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),code,reading:r,notes:$('#notes').value.trim()});persist(a);$('#progress').textContent='Lettura salvata sul dispositivo.'};
$('#clear').onclick=()=>{$('#meterCode').value=$('#reading').value=$('#notes').value=$('#raw').textContent=$('#meterHint').textContent='';$('#progress').textContent=''};
function render(){const a=load();$('#history').innerHTML=a.map(x=>`<tr><td>${new Date(x.date).toLocaleString('it-IT')}</td><td>${esc(x.code)}</td><td>${esc(x.reading)}</td><td>${esc(x.notes)}</td><td><button class="secondary" data-del="${x.id}">×</button></td></tr>`).join('')||'<tr><td colspan="5">Nessuna lettura</td></tr>';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>persist(load().filter(x=>x.id!==b.dataset.del)))}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#csv').onclick=()=>{const a=load();if(!a.length)return alert('Nessun dato da esportare.');const rows=[['Data','Codice contatore','Lettura kWh','Note'],...a.map(x=>[new Date(x.date).toLocaleString('it-IT'),x.code,x.reading,x.notes])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n');const u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),ael=document.createElement('a');ael.href=u;ael.download='letture_contatori.csv';ael.click();URL.revokeObjectURL(u)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();