/* V5.1 TEST - aree contatore, ID e display con verifica incrociata */
(()=>{
const q=s=>document.querySelector(s),canvas=q('#preview'),ctx=canvas.getContext('2d',{willReadFrequently:true});
let image=null,start=null,selection=null,crop=null,meterCrop=null,idCrop=null,mode='meter',boxes={meter:null,id:null,display:null},lastOcr={confidence:null,candidates:[],unit:null};
const STORE='meter-guided-readings-v1';
const previousMWh={"QC30":7033.502,"QCPA1":5220.67,"QCPA2":5290.63,"QCPA4":197.338,"QCPA5":3956.261,"QE1":4872.63,"QE2":368.81,"QE4":2124.72,"QK1/13":0.481,"QK14":585.61,"QK2/1":503.397,"QK20":8.961,"QK21":881.995,"QK22":433.366,"QK23":117.568,"QK24":100.375,"QK26":32781.71,"QK27":547.034,"QK29":498.872,"QK30":700.477,"QK31":440.387,"QK32":555.997,"QK7/1":757.609,"QK7/2":761.955,"QK7/3":218.065,"QKA2":1455.635,"QKL1":188.299,"QKL10":956.659,"QKL11":350.383,"QKL12":620.09,"QKL13":607.56,"QKL16":242.374,"QKL17":345.93,"QKL18":1333.459,"QKL3":581.091,"QKL4":382.674,"QKL5":505.185,"QKL6":199.6,"QKL8":874.91,"QKL9":474.066,"QKR1":2839.75,"QKR2":1930.43,"QKR3":716.865,"QKR4":166.999,"QKR5":998.381,"QL15":7932.3,"QL20":905.728,"QL21":655.662,"QL26":622.629,"QL27":153.584,"QL7/1":153.245,"QL7/2":283.216,"QL7/3":645.736,"QPW-01":2303.943,"QSGC2":21105.8};
const data=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}};
const persist=a=>{localStorage.setItem(STORE,JSON.stringify(a));render()};
async function decode(file){try{if('createImageBitmap'in window)return await createImageBitmap(file,{imageOrientation:'from-image'})}catch{}return await new Promise((ok,no)=>{const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);ok(i)};i.onerror=no;i.src=u})}
async function loadPhoto(input){const file=input.files?.[0];if(!file)return;q('#progress').textContent='Caricamento foto…';try{image=await decode(file);const scale=Math.min(1,2200/image.width);canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);ctx.drawImage(image,0,0,canvas.width,canvas.height);q('#cropWrap').style.display='block';clearSelection();q('#cropHint').textContent='Trascina un rettangolo intorno alle cifre del display.';q('#progress').textContent='Foto pronta.'}catch(e){q('#progress').textContent='Impossibile aprire la foto: '+e.message}input.value=''}
q('#cameraPhoto').onchange=e=>loadPhoto(e.target);q('#libraryPhoto').onchange=e=>loadPhoto(e.target);
function pos(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
function makeBox(a,b){return{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)}}
function cssBox(el,b){if(!b){el.style.display='none';return}el.style.display='block';el.style.left=b.x*100+'%';el.style.top=b.y*100+'%';el.style.width=b.w*100+'%';el.style.height=b.h*100+'%'}
function showBox(){cssBox(q('#selection'),selection);cssBox(q('#meterBox'),boxes.meter);cssBox(q('#idBox'),boxes.id)}
function setMode(m){mode=m;q('#modeMeter').className=m==='meter'?'':'secondary';q('#modeId').className=m==='id'?'':'secondary';q('#modeDisplay').className=m==='display'?'':'secondary';q('#cropHint').textContent=m==='meter'?'Delimita l’intero contatore.':m==='id'?'Delimita la targhetta con l’ID.':'Delimita esclusivamente le cifre e l’unità del display.'}
function clearSelection(){start=selection=crop=meterCrop=idCrop=null;boxes={meter:null,id:null,display:null};showBox();q('#cropCheck').style.display='none';q('#idCheck').textContent='Controllo ID non ancora eseguito.';q('#idCheck').className='notice neutral';q('#analyze').disabled=true;q('#resetCrop').disabled=true;setMode('meter')}
function buildCrop(b){if(!b)return null;const x=Math.round(b.x*canvas.width),y=Math.round(b.y*canvas.height),w=Math.max(1,Math.round(b.w*canvas.width)),h=Math.max(1,Math.round(b.h*canvas.height)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(canvas,x,y,w,h,0,0,w,h);return c}
function preview(el,c){el.width=c.width;el.height=c.height;el.getContext('2d').drawImage(c,0,0)}
q('#modeMeter').onclick=()=>setMode('meter');q('#modeId').onclick=()=>setMode('id');q('#modeDisplay').onclick=()=>setMode('display');
q('#cropWrap').addEventListener('pointerdown',e=>{if(!image)return;e.preventDefault();start=pos(e);selection={x:start.x,y:start.y,w:0,h:0};q('#cropWrap').setPointerCapture?.(e.pointerId);showBox()});
q('#cropWrap').addEventListener('pointermove',e=>{if(!start)return;e.preventDefault();selection=makeBox(start,pos(e));showBox()});
q('#cropWrap').addEventListener('pointerup',e=>{if(!start)return;e.preventDefault();const b=makeBox(start,pos(e));start=null;const r=canvas.getBoundingClientRect();if(b.w*r.width<45||b.h*r.height<20){selection=null;showBox();q('#cropHint').textContent='Selezione troppo piccola. Riprova.';return}boxes[mode]=b;selection=null;if(mode==='meter'){meterCrop=buildCrop(b);preview(q('#meterPreview'),meterCrop);setMode('id')}else if(mode==='id'){idCrop=buildCrop(b);preview(q('#idPreview'),idCrop);setMode('display')}else{crop=buildCrop(b);preview(q('#cropPreview'),crop)}q('#cropCheck').style.display='grid';q('#analyze').disabled=!(meterCrop&&idCrop&&crop);q('#resetCrop').disabled=false;if(meterCrop&&idCrop&&crop)q('#cropHint').textContent='Tre aree definite. Verifica le anteprime prima dell’analisi.';showBox()});
q('#resetCrop').onclick=()=>clearSelection();
function preprocess(src,mode){const scale=Math.min(4,Math.max(2,1200/src.width)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(src.width*scale));c.height=Math.max(1,Math.round(src.height*scale));const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0,c.width,c.height);const im=x.getImageData(0,0,c.width,c.height),d=im.data;let sum=0;for(let i=0;i<d.length;i+=4)sum+=.299*d[i]+.587*d[i+1]+.114*d[i+2];const mean=sum/(d.length/4);for(let i=0;i<d.length;i+=4){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2];g=(g-mean)*(mode==='soft'?1.7:2.6)+128;if(mode==='binary')g=g>135?255:0;g=Math.max(0,Math.min(255,g));d[i]=d[i+1]=d[i+2]=g}x.putImageData(im,0,0);return c}
function parseCandidates(text){let t=String(text||'').replace(/[Oo]/g,'0').replace(/,/g,'.'),out=[];for(const m of t.matchAll(/\d[\d .]{2,}\d/g)){let s=m[0].replace(/\s/g,'');if((s.match(/\./g)||[]).length>1){const p=s.lastIndexOf('.');s=s.slice(0,p).replace(/\./g,'')+'.'+s.slice(p+1)}if(/^\d{3,10}(?:\.\d{1,3})?$/.test(s)&&!/(\d)\1{5,}/.test(s.replace('.','')))out.push(s)}return [...new Set(out)]}
async function recognize(img,label){return await Tesseract.recognize(img,'eng',{tessedit_char_whitelist:'0123456789., kWhMWhKWHMWH',tessedit_pageseg_mode:'7',preserve_interword_spaces:'1',logger:m=>{if(m.status==='recognizing text')q('#progress').textContent=label+': '+Math.round((m.progress||0)*100)+'%'}})}
function normId(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function distance(a,b){a=normId(a);b=normId(b);const d=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)d[i][0]=i;for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}
async function recognizeId(){const r=await Tesseract.recognize(preprocess(idCrop,'hard'),'eng',{tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/- ',tessedit_pageseg_mode:'7',preserve_interword_spaces:'1',logger:m=>{if(m.status==='recognizing text')q('#progress').textContent='Controllo ID: '+Math.round((m.progress||0)*100)+'%'}}),expected=q('#meterId').value,raw=(r.data.text||'').trim(),flat=normId(raw),target=normId(expected);let best=99;if(flat.includes(target))best=0;else{for(const token of flat.match(/[A-Z0-9]+/g)||[flat])best=Math.min(best,distance(token,target))}const ok=expected&&best<=1,el=q('#idCheck');el.textContent=!expected?'Seleziona prima l’ID dall’archivio.':ok?'ID verificato: area letta “'+raw+'”, compatibile con '+expected+'.':'ID non confermato: area letta “'+(raw||'nessun testo')+'”, atteso '+expected+'. Controlla area e contatore.';el.className='notice '+(ok?'ok':'warning');return{raw,confidence:Math.round(r.data.confidence||0),distance:best,ok}}
async function analyze(){if(!meterCrop||!idCrop||!crop)return;q('#analyze').disabled=true;try{q('#progress').textContent='Controllo preliminare dell’ID…';const idResult=await recognizeId();const runs=[];for(const mode of ['soft','hard','binary']){const r=await recognize(preprocess(crop,mode),'OCR '+mode);runs.push({mode,text:r.data.text,confidence:r.data.confidence||0,candidates:parseCandidates(r.data.text)})}const votes={};for(const r of runs)for(const s of r.candidates){votes[s]??={value:s,count:0,confidence:0};votes[s].count++;votes[s].confidence=Math.max(votes[s].confidence,r.confidence)}const ranked=Object.values(votes).sort((a,b)=>b.count-a.count||b.confidence-a.confidence),best=ranked[0];const allText=runs.map(r=>r.text).join(' '),unit=/m\s*w\s*h/i.test(allText)?'MWh':/k\s*w\s*h/i.test(allText)?'kWh':null;lastOcr={confidence:best?Math.round(best.confidence):0,candidates:ranked,unit};if(best)q('#reading').value=best.value;if(unit)q('#readingUnit').value=unit;const high=best&&best.count>=2&&best.confidence>=60;q('#confidence').textContent=best?(high?'Confidenza OCR alta':'Confidenza OCR limitata: controllare attentamente il valore')+' · accordo '+best.count+'/3 · '+Math.round(best.confidence)+'%':'Nessuna lettura affidabile. Inserisci il valore manualmente.';q('#confidence').className=high?'notice ok':'notice warning';q('#raw').textContent='--- CONTROLLO ID · '+idResult.confidence+'% ---\nLetto: '+(idResult.raw||'nessun testo')+'\nDistanza: '+idResult.distance+'\nEsito: '+(idResult.ok?'compatibile':'da verificare')+'\n\n'+runs.map(r=>'--- '+r.mode.toUpperCase()+' · '+Math.round(r.confidence)+'% ---\n'+r.text+'Candidati: '+(r.candidates.join(', ')||'nessuno')).join('\n\n');q('#progress').textContent='Analisi completata. La conferma dell’operatore resta necessaria.';updateReview()}catch(e){q('#progress').textContent='Errore OCR: '+e.message;q('#confidence').textContent='OCR non disponibile. Inserisci la lettura manualmente.';q('#confidence').className='notice warning'}finally{q('#analyze').disabled=!crop}}
q('#analyze').onclick=analyze;
function numeric(){const t=q('#reading').value.trim().replace(',','.');if(!/^\d+(?:\.\d+)?$/.test(t))return null;const n=Number(t);return Number.isFinite(n)&&n>=0?n:null}
function toMWh(n){return q('#readingUnit').value==='kWh'?n/1000:n}
function reviewState(){const id=q('#meterId').value,n=numeric();if(!id||n===null)return{level:'neutral',text:'Seleziona ID e inserisci una lettura numerica valida.',mwh:null};const mwh=toMWh(n),prev=previousMWh[id];if(!Number.isFinite(prev))return{level:'neutral',text:'Nessun valore storico numerico utilizzabile per questo ID.',mwh};const delta=mwh-prev,pct=prev?delta/prev:null;if(mwh<prev*.95)return{level:'warning',text:'Attenzione: la lettura è inferiore allo storico ('+prev.toLocaleString('it-IT')+' MWh). Verificare unità, cifre, eventuale azzeramento o sostituzione.',mwh};if(delta>Math.max(5,prev*.5))return{level:'warning',text:'Incremento molto elevato rispetto allo storico: +'+delta.toLocaleString('it-IT',{maximumFractionDigits:3})+' MWh. Controllare cifra e unità.',mwh};return{level:'ok',text:'Controllo di plausibilità superato rispetto allo storico disponibile. Incremento: +'+delta.toLocaleString('it-IT',{maximumFractionDigits:3})+' MWh.',mwh}}
function updateReview(){const n=numeric(),m=n===null?null:toMWh(n),r=reviewState();q('#conversion').textContent='Valore da registrare: '+(m===null?'—':m.toLocaleString('it-IT',{maximumFractionDigits:6}))+' MWh';q('#plausibility').textContent=r.text;q('#plausibility').className='notice '+r.level;const opt=q('#meterId').selectedOptions[0];q('#meterDescription').textContent=q('#meterId').value?(opt.textContent+' · ultimo storico disponibile: '+(Number.isFinite(previousMWh[q('#meterId').value])?previousMWh[q('#meterId').value].toLocaleString('it-IT')+' MWh':'non numerico/assente')):'Seleziona un ID presente nell’archivio Excel.'}
q('#meterId').onchange=updateReview;q('#reading').oninput=updateReview;q('#readingUnit').onchange=updateReview;
q('#saveReading').onclick=()=>{const id=q('#meterId').value,n=numeric(),r=reviewState();if(!id)return alert('Seleziona l’ID del contatore.');if(n===null)return alert('Inserisci una lettura numerica valida.');const rec={date:new Date().toISOString(),id,reading:n,unit:q('#readingUnit').value,readingMWh:r.mwh,plausibility:r.level,ocrConfidence:lastOcr.confidence,notes:q('#notes').value.trim()};const a=data();a.push(rec);persist(a);q('#progress').textContent='Lettura salvata: '+id+' · '+n+' '+rec.unit+' · '+rec.readingMWh.toLocaleString('it-IT',{maximumFractionDigits:6})+' MWh.'};
q('#clearReading').onclick=()=>{q('#reading').value='';q('#notes').value='';lastOcr={confidence:null,candidates:[],unit:null};q('#confidence').textContent='OCR non ancora eseguito.';q('#confidence').className='muted';q('#raw').textContent='';updateReview()};
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const a=data();q('#history').innerHTML=a.slice().reverse().map((r,rev)=>'<tr><td>'+new Date(r.date).toLocaleString('it-IT')+'</td><td>'+esc(r.id)+'</td><td>'+esc(r.reading)+' '+esc(r.unit)+'</td><td>'+Number(r.readingMWh).toLocaleString('it-IT',{maximumFractionDigits:6})+'</td><td>'+esc(r.plausibility)+'</td><td><button class="secondary deleteRow" data-i="'+(a.length-1-rev)+'">×</button></td></tr>').join('')||'<tr><td colspan="6">Nessuna lettura acquisita</td></tr>';document.querySelectorAll('.deleteRow').forEach(b=>b.onclick=()=>{const z=data();z.splice(Number(b.dataset.i),1);persist(z)})}
q('#csv').onclick=()=>{const rows=[['Data ISO','ID contatore','Lettura originale','Unità originale','Lettura MWh','Esito plausibilità','Confidenza OCR','Note'],...data().map(r=>[r.date,r.id,r.reading,r.unit,r.readingMWh,r.plausibility,r.ocrConfidence??'',r.notes])],csv=rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n'),u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='letture_contatori_MWh.csv';a.click();URL.revokeObjectURL(u)};
render();updateReview();
})();