/* V4.7 multi-modello: una selezione contatore+targhetta, OCR codice prima, poi display per famiglia. */
const V47_PROFILES={
 'IME NEMO 144':[[.10,.08,.80,.30],[.08,.16,.84,.34],[.16,.10,.68,.42]],
 'Electrex VIPD3':[[.06,.06,.88,.38],[.06,.14,.88,.44],[.12,.08,.76,.50]],
 'IME CONTO D4-Pt':[[.08,.05,.84,.34],[.10,.12,.80,.42],[.16,.08,.68,.48]],
 'IME NEMO D4-Le':[[.08,.05,.84,.34],[.10,.12,.80,.42],[.16,.08,.68,.48]],
 'IME NEMO':[[.08,.05,.84,.34],[.10,.12,.80,.42],[.16,.08,.68,.48]]
};
function v47Tokens(t){return String(t||'').toUpperCase().match(/[A-Z0-9/. -]{3,}/g)||[]}
function v47Meter(text){const tokens=v47Tokens(text),flat=norm(text);let best=null;for(const m of METERS)for(const a of m.aliases){const na=norm(a);if(flat.includes(na))return{meter:m,dist:0,raw:a};for(const tok of tokens){const nt=norm(tok);for(let start=0;start<nt.length;start++)for(let len=Math.max(2,na.length-2);len<=Math.min(nt.length-start,na.length+2);len++){const q=nt.slice(start,start+len),d=lev(q,na);if(d<=2&&(!best||d<best.dist||(d===best.dist&&na.length>best.len)))best={meter:m,dist:d,len:na.length,raw:q}}}}return best}
function v47ReadingCandidates(text){let t=String(text||'').replace(/[Oo]/g,'0').replace(/,/g,'.'),out=[];for(const m of t.matchAll(/\d[\d .]{2,}\d/g)){let s=m[0].replace(/\s/g,'');if((s.match(/\./g)||[]).length>1){const p=s.lastIndexOf('.');s=s.slice(0,p).replace(/\./g,'')+'.'+s.slice(p+1)}if(/^\d{3,9}(?:\.\d{1,3})?$/.test(s)&&!/(\d)\1{4,}/.test(s.replace('.','')))out.push(s)}return [...new Set(out)]}
function v47Score(s,text,meter,roi){const digits=s.replace('.','').length,dec=s.includes('.')?(s.split('.')[1]||'').length:0;let q=0;if(digits>=6&&digits<=8)q+=120;else if(digits>=4)q+=35;if(dec===1)q+=150;else if(dec===2)q+=110;else if(dec===3)q+=30;if(/k\s*w\s*h/i.test(text))q+=150;if(/m\s*w\s*h/i.test(text))q+=120;if(/\bET\b/i.test(text))q+=90;if(meter?.family==='Electrex VIPD3'&&dec===2)q+=90;if((meter?.family||'').includes('NEMO')&&dec===1)q+=45;if(Number(s)>=1000)q+=20;q-=roi*3;return q}
async function v47CodeOCR(){const opts={tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/.- ',tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'},areas=[['FULL',subCrop(selectedCrop,0,0,1,1,1)],['LOW',subCrop(selectedCrop,0,.48,1,.52,1.5)],['MIDLOW',subCrop(selectedCrop,.05,.35,.90,.60,1.4)]];let logs=[],best=null;for(const [name,img] of areas){const a=await ocr(enhance(img,1.8),`Codice ${name}`,opts),b=await ocr(enhance(img,2.6,165),`Codice ${name} B`,opts),txt=a.text+' '+b.text,hit=v47Meter(txt);logs.push(`${name}:\n${txt}`);if(hit&&(!best||hit.dist<best.dist))best=hit}return{best,logs}}
async function v47DisplayOCR(meter){let rois=V47_PROFILES[meter?.family]||[[.05,.03,.90,.30],[.05,.12,.90,.36],[.08,.22,.84,.38],[.15,.05,.70,.50]];let all=[],logs=[],bestPreview=null;const opts7={tessedit_char_whitelist:'0123456789.,kWhMWhET ',tessedit_pageseg_mode:'7',preserve_interword_spaces:'1'},opts6={...opts7,tessedit_pageseg_mode:'6'};for(let i=0;i<rois.length;i++){const [x,y,w,h]=rois[i],raw=subCrop(selectedCrop,x,y,w,h,1),big=subCrop(raw,0,0,1,1,2.5),runs=[['G',await ocr(enhance(big,1.7),`Display ${i+1} G`,opts7)],['T',await ocr(enhance(big,2.5,160),`Display ${i+1} T`,opts7)],['B',await ocr(enhance(big,2.1),`Display ${i+1} B`,opts6)]];logs.push(`ROI ${i+1} x=${x} y=${y} w=${w} h=${h}\n`+runs.map(([n,d])=>`${n}: ${d.text}`).join('\n'));for(const [run,d] of runs)for(const s of v47ReadingCandidates(d.text))all.push({s,score:v47Score(s,d.text,meter,i),roi:i,run,text:d.text,raw})}all.sort((a,b)=>b.score-a.score);if(all[0])bestPreview=all[0].raw;else bestPreview=subCrop(selectedCrop,...rois[0],1);return{all,logs,bestPreview}}
async function v47Analyze(){if(!selectedCrop)return;$('#analyze').disabled=true;try{$('#progress').textContent='V4.7: riconoscimento codice…';const manual=byCode($('#knownMeter').value),code=await v47CodeOCR(),meter=manual||code.best?.meter;$('#progress').textContent=`V4.7: ricerca display${meter?' · '+meter.family:''}…`;const disp=await v47DisplayOCR(meter),best=disp.all[0];if(disp.bestPreview)setPreview(lcdPreview,disp.bestPreview);setPreview(codePreview,subCrop(selectedCrop,0,.40,1,.60,1));$('#segmentCheck').style.display='block';$('#meterCode').value=meter?.code||'';$('#reading').value=best?.s||'';$('#meterHint').textContent=meter?`Codice: ${meter.code} · ${meter.family}${manual?' (selezionato)':' · riconoscimento tollerante'}`:'Codice non identificato.';$('#raw').textContent=`--- V4.7 OCR MULTI-MODELLO ---\nArea: ${selectedCrop.width}x${selectedCrop.height}px\nModello: ${meter?.family||'non identificato'}\nCodice match: ${code.best?code.best.meter.code+' dist='+code.best.dist+' raw='+code.best.raw:'nessuno'}\n--- OCR CODICE ---\n${code.logs.join('\n---\n')}\n--- ROI DISPLAY ---\n${disp.logs.join('\n---\n')}\n--- CANDIDATI ---\n${disp.all.slice(0,15).map(v=>`${v.s} | score ${v.score} | ROI ${v.roi+1}/${v.run}`).join('\n')||'nessuno'}`;$('#progress').textContent=best?'Analisi completata. Verifica codice, lettura e anteprima display.':'Nessuna lettura affidabile individuata.'}catch(e){$('#progress').textContent='Errore OCR V4.7: '+e.message}finally{$('#analyze').disabled=!selectedCrop}}
$('#analyze').onclick=v47Analyze;