/* V4.8: iterazione sui modelli fotografici. Corregge i falsi match (es. COM->QCAP1) e cerca il display con ROI compatte. */
function v48Meter(text){const flat=norm(text),tokens=(String(text||'').toUpperCase().match(/[A-Z0-9/.]+/g)||[]).map(norm);let best=null;for(const m of METERS)for(const a of m.aliases){const na=norm(a);if(na.length<4)continue;if(flat.includes(na))return{meter:m,dist:0,raw:na};for(const t of tokens){if(t.length<na.length-1||t.length>na.length+1)continue;if(t[0]!==na[0])continue;const d=lev(t,na);if(d<=1&&(!best||d<best.dist||d===best.dist&&na.length>best.len))best={meter:m,dist:d,len:na.length,raw:t}}}return best}
const V48_ROIS={
 'IME NEMO':[[.12,.02,.64,.16],[.16,.08,.58,.16],[.10,.14,.68,.18],[.18,.20,.58,.16],[.08,.28,.70,.18],[.20,.34,.56,.16]],
 'IME NEMO 144':[[.28,.08,.66,.18],[.30,.16,.64,.18],[.26,.24,.68,.18],[.22,.32,.72,.18],[.18,.40,.76,.18]],
 'Electrex VIPD3':[[.10,.34,.72,.18],[.12,.42,.72,.18],[.10,.50,.74,.20],[.12,.58,.72,.20],[.16,.66,.68,.18]],
 'IME NEMO D4-Le':[[.12,.36,.62,.16],[.14,.44,.60,.16],[.12,.52,.62,.16],[.14,.60,.60,.18],[.16,.68,.58,.18]],
 'IME CONTO D4-Pt':[[.14,.34,.62,.16],[.14,.42,.62,.16],[.14,.50,.62,.16],[.14,.58,.62,.18],[.16,.66,.58,.18]]
};
function v48Pre(src,mode){const c=document.createElement('canvas');c.width=src.width*3;c.height=src.height*3;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0,c.width,c.height);const im=x.getImageData(0,0,c.width,c.height),d=im.data;let vals=[],sum=0;for(let i=0;i<d.length;i+=4){const g=mode==='green'?d[i+1]:.299*d[i]+.587*d[i+1]+.114*d[i+2];vals.push(g);sum+=g}const mean=sum/vals.length;for(let p=0,i=0;i<d.length;i+=4,p++){let g=vals[p];g=(g-mean)*2.7+128;if(mode==='binary')g=g>128?255:0;g=Math.max(0,Math.min(255,g));d[i]=d[i+1]=d[i+2]=g}x.putImageData(im,0,0);return c}
async function v48CodeOCR(){const opts={tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/.- ',tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'},areas=[['FULL',subCrop(selectedCrop,0,0,1,1,.75)],['TOP',subCrop(selectedCrop,0,0,1,.45,1.2)],['LOW',subCrop(selectedCrop,0,.45,1,.55,1.2)]];let logs=[],best=null;for(const [name,img] of areas){const d=await ocr(enhance(img,2.1),`Codice ${name}`,opts),hit=v48Meter(d.text);logs.push(`${name}:\n${d.text}`);if(hit&&(!best||hit.dist<best.dist))best=hit}return{best,logs}}
function v48Cand(text){let t=String(text||'').replace(/[Oo]/g,'0').replace(/,/g,'.'),out=[];for(const m of t.matchAll(/\d[\d .]{2,}\d/g)){let s=m[0].replace(/\s/g,'');if((s.match(/\./g)||[]).length>1){const p=s.lastIndexOf('.');s=s.slice(0,p).replace(/\./g,'')+'.'+s.slice(p+1)}if(/^\d{4,9}(?:\.\d{1,3})?$/.test(s)&&!/(\d)\1{4,}/.test(s.replace('.','')))out.push(s)}return [...new Set(out)]}
function v48Score(s,text,meter,idx){const n=s.replace('.','').length,dec=(s.split('.')[1]||'').length;let q=0;if(n>=6&&n<=8)q+=160;else if(n>=5)q+=70;if(dec===1)q+=170;if(dec===2)q+=120;if(dec===3)q+=20;if(/k\s*w\s*h/i.test(text))q+=180;if(/m\s*w\s*h/i.test(text))q+=160;if(/\bET\b/i.test(text))q+=100;if(meter?.family==='Electrex VIPD3'&&dec===2)q+=60;if((meter?.family||'').includes('NEMO')&&dec===1)q+=45;q-=idx*2;return q}
async function v48DisplayOCR(meter){const fam=meter?.family||'IME NEMO',rois=V48_ROIS[fam]||V48_ROIS['IME NEMO'];const opts={tessedit_char_whitelist:'0123456789.,kWhMWhET ',tessedit_pageseg_mode:'7',preserve_interword_spaces:'1'};let first=[],logs=[];for(let i=0;i<rois.length;i++){const raw=subCrop(selectedCrop,...rois[i],1),d=await ocr(v48Pre(raw,'green'),`Display ${i+1}`,opts);logs.push(`ROI ${i+1} ${rois[i].join(',')}\nG: ${d.text}`);for(const s of v48Cand(d.text))first.push({s,score:v48Score(s,d.text,meter,i),i,raw,text:d.text,run:'G'})}first.sort((a,b)=>b.score-a.score);const retry=[...new Set(first.slice(0,2).map(v=>v.i).concat([0,1]))].slice(0,3);for(const i of retry){const raw=subCrop(selectedCrop,...rois[i],1);for(const mode of ['gray','binary']){const d=await ocr(v48Pre(raw,mode),`Display ${i+1} ${mode}`,opts);logs.push(`ROI ${i+1} ${mode}: ${d.text}`);for(const s of v48Cand(d.text))first.push({s,score:v48Score(s,d.text,meter,i)+(mode==='gray'?5:0),i,raw,text:d.text,run:mode})}}first.sort((a,b)=>b.score-a.score);return{all:first,logs,bestPreview:first[0]?.raw||subCrop(selectedCrop,...rois[0],1)}}
async function v48Analyze(){if(!selectedCrop)return;$('#analyze').disabled=true;try{$('#progress').textContent='V4.8: codice…';const manual=byCode($('#knownMeter').value),code=await v48CodeOCR(),meter=manual||code.best?.meter;$('#progress').textContent=`V4.8: display${meter?' · '+meter.family:''}…`;const disp=await v48DisplayOCR(meter),best=disp.all[0];setPreview(lcdPreview,disp.bestPreview);setPreview(codePreview,subCrop(selectedCrop,0,0,1,1,1));$('#segmentCheck').style.display='block';$('#meterCode').value=meter?.code||'';$('#reading').value=best?.s||'';$('#meterHint').textContent=meter?`Codice: ${meter.code} · ${meter.family}${manual?' (selezionato)':' · match rigoroso'}`:'Codice non identificato: nessun modello viene forzato.';$('#raw').textContent=`--- V4.8 OCR ITERATIVO ---\nArea: ${selectedCrop.width}x${selectedCrop.height}px\nModello: ${meter?.family||'non identificato'}\nCodice: ${code.best?code.best.meter.code+' dist='+code.best.dist+' raw='+code.best.raw:'nessuno'}\n--- CODICE ---\n${code.logs.join('\n---\n')}\n--- DISPLAY ---\n${disp.logs.join('\n---\n')}\n--- CANDIDATI ---\n${disp.all.slice(0,15).map(v=>`${v.s} | score ${v.score} | ROI ${v.i+1}/${v.run}`).join('\n')||'nessuno'}`;$('#progress').textContent=best?'Analisi completata.':'Nessuna lettura affidabile.'}catch(e){$('#progress').textContent='Errore OCR V4.8: '+e.message}finally{$('#analyze').disabled=!selectedCrop}}
$('#analyze').onclick=v48Analyze;