/* V4.9: localizzazione adattiva del display. Il codice resta V4.8; il display viene cercato nell'immagine prima dell'OCR. */
const V49_FAMILY_HINT={
 'IME NEMO':{y:[.02,.55],aspect:[1.5,6.8]},
 'IME NEMO 144':{y:[.02,.62],aspect:[1.5,7.5]},
 'Electrex VIPD3':{y:[.08,.78],aspect:[1.4,7.5]},
 'IME NEMO D4-Le':{y:[.08,.78],aspect:[1.4,7.5]},
 'IME CONTO D4-Pt':{y:[.08,.78],aspect:[1.4,7.5]}
};
function v49GrayStats(src,cols=48,rows=48){const c=document.createElement('canvas');c.width=cols;c.height=rows;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(src,0,0,cols,rows);const d=x.getImageData(0,0,cols,rows).data,a=new Float32Array(cols*rows);for(let i=0,p=0;i<d.length;i+=4,p++)a[p]=.299*d[i]+.587*d[i+1]+.114*d[i+2];return{a,cols,rows}}
function v49RegionScore(st,x0,y0,x1,y1,hint){const {a,cols,rows}=st;let n=0,sum=0,sum2=0,edge=0;for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const v=a[y*cols+x];n++;sum+=v;sum2+=v*v;if(x+1<x1)edge+=Math.abs(v-a[y*cols+x+1]);if(y+1<y1)edge+=.45*Math.abs(v-a[(y+1)*cols+x])}const mean=sum/n,sd=Math.sqrt(Math.max(0,sum2/n-mean*mean)),asp=(x1-x0)/(y1-y0),cy=((y0+y1)/2)/rows;let q=edge/n*.9+sd*.55;if(mean>55&&mean<225)q+=8;if(asp>=hint.aspect[0]&&asp<=hint.aspect[1])q+=12;if(cy>=hint.y[0]&&cy<=hint.y[1])q+=10;q-=Math.abs(cy-(hint.y[0]+hint.y[1])/2)*8;return q}
function v49Locate(src,meter){const st=v49GrayStats(src),hint=V49_FAMILY_HINT[meter?.family]||{y:[.02,.80],aspect:[1.4,8]},out=[];for(let h=6;h<=14;h+=2)for(let w=14;w<=38;w+=4)for(let y=1;y+h<st.rows-1;y+=3)for(let x=1;x+w<st.cols-1;x+=3){const cy=(y+h/2)/st.rows;if(cy<hint.y[0]-.12||cy>hint.y[1]+.12)continue;out.push({x:x/st.cols,y:y/st.rows,w:w/st.cols,h:h/st.rows,score:v49RegionScore(st,x,y,x+w,y+h,hint)})}out.sort((a,b)=>b.score-a.score);const keep=[];for(const r of out){if(keep.every(k=>Math.abs((k.x+k.w/2)-(r.x+r.w/2))>.08||Math.abs((k.y+k.h/2)-(r.y+r.h/2))>.06))keep.push(r);if(keep.length===8)break}return keep}
function v49Expand(r,p=.025){return{x:Math.max(0,r.x-p),y:Math.max(0,r.y-p),w:Math.min(1,r.x+r.w+p)-Math.max(0,r.x-p),h:Math.min(1,r.y+r.h+p)-Math.max(0,r.y-p)}}
async function v49DisplayOCR(meter){const loc=v49Locate(selectedCrop,meter),opts7={tessedit_char_whitelist:'0123456789.,kWhMWhET ',tessedit_pageseg_mode:'7',preserve_interword_spaces:'1'},all=[],logs=[];for(let i=0;i<loc.length;i++){const r=v49Expand(loc[i]),raw=subCrop(selectedCrop,r.x,r.y,r.w,r.h,1);for(const mode of ['green','gray']){const d=await ocr(v48Pre(raw,mode),`V4.9 display ${i+1} ${mode}`,opts7);logs.push(`REG ${i+1} localizer=${loc[i].score.toFixed(1)} x=${r.x.toFixed(3)} y=${r.y.toFixed(3)} w=${r.w.toFixed(3)} h=${r.h.toFixed(3)} ${mode}: ${d.text}`);for(const s of v48Cand(d.text)){let q=v48Score(s,d.text,meter,i)+loc[i].score*.35;if(s.replace('.','').length>=6)q+=80;if(s.includes('.'))q+=50;all.push({s,score:q,i,raw,text:d.text,run:mode,region:r})}}if(all.some(v=>v.score>360))break}all.sort((a,b)=>b.score-a.score);return{all,logs,regions:loc,bestPreview:all[0]?.raw||(loc[0]?subCrop(selectedCrop,...Object.values(v49Expand(loc[0])),1):selectedCrop)}}
async function v49Analyze(){if(!selectedCrop)return;$('#analyze').disabled=true;try{$('#progress').textContent='V4.9: riconoscimento codice…';const manual=byCode($('#knownMeter').value),code=await v48CodeOCR(),meter=manual||code.best?.meter;$('#progress').textContent=`V4.9: localizzazione fisica display${meter?' · '+meter.family:''}…`;const disp=await v49DisplayOCR(meter),best=disp.all[0];setPreview(lcdPreview,disp.bestPreview);setPreview(codePreview,selectedCrop);$('#segmentCheck').style.display='block';$('#meterCode').value=meter?.code||'';$('#reading').value=best?.s||'';$('#meterHint').textContent=meter?`Codice: ${meter.code} · ${meter.family}${manual?' (selezionato)':' · match rigoroso'} · display localizzato indipendentemente`:'Codice non identificato · ricerca display indipendente';$('#raw').textContent=`--- V4.9 DISPLAY LOCALIZER ---\nArea: ${selectedCrop.width}x${selectedCrop.height}px\nModello: ${meter?.family||'non identificato'}\nCodice: ${code.best?code.best.meter.code+' dist='+code.best.dist+' raw='+code.best.raw:'nessuno'}\nRegioni candidate: ${disp.regions.length}\n--- CODICE ---\n${code.logs.join('\n---\n')}\n--- DISPLAY LOCALIZZATO ---\n${disp.logs.join('\n---\n')}\n--- CANDIDATI ---\n${disp.all.slice(0,20).map(v=>`${v.s} | score ${v.score.toFixed(1)} | REG ${v.i+1}/${v.run}`).join('\n')||'nessuno'}`;$('#progress').textContent=best?'Analisi completata: verifica soprattutto anteprima display.':'Display cercato, nessuna lettura affidabile.'}catch(e){$('#progress').textContent='Errore OCR V4.9: '+e.message}finally{$('#analyze').disabled=!selectedCrop}}
$('#analyze').onclick=v49Analyze;
