(()=>{
  const q=s=>document.querySelector(s),api=window.MeterProfiles;if(!api)return;
  const id=q('#meterId'),digits=q('#digitCount'),decimals=q('#decimalPlaces'),unit=q('#readingUnit'),reading=q('#reading'),analyze=q('#analyze'),confidence=q('#confidence'),progress=q('#progress');
  const quality=document.createElement('div');quality.id='imageQuality';quality.className='notice neutral';quality.textContent='Qualità immagine: seleziona il display.';(q('#cropCheck')||analyze).insertAdjacentElement('afterend',quality);
  const badge=document.createElement('div');badge.id='meterProfile';badge.className='notice neutral';(q('#localModelStatus')||id).insertAdjacentElement('afterend',badge);
  function applyProfile(){const p=api.profile(id.value);badge.textContent=p.family==='unknown'?'Profilo display: generico. Seleziona manualmente la sola riga energia.':'Profilo display: '+p.label+' · '+p.digits+' cifre · '+p.decimals+' decimali · '+p.unit+'.';if(p.digits)digits.value=String(p.digits);if(p.decimals!==null)decimals.value=String(p.decimals);if(p.unit)unit.value=p.unit;return p}
  function check(){if(!id.value||!reading.value.trim())return;const r=api.validate(reading.value,id.value,unit.value);const target=q('#plausibility');if(!r.ok){target.textContent='Controllo profilo: '+r.reason+'. Verifica il display prima di salvare.';target.className='notice warning';confidence.textContent='Il candidato OCR non rispetta il formato noto di '+id.value+'.';confidence.className='notice warning'}else if(r.value!==reading.value.trim().replace(',','.')){reading.value=r.value;reading.dispatchEvent(new Event('input',{bubbles:true}));progress.textContent='Separatore decimale ricostruito dal profilo '+id.value+': '+r.value+' '+r.profile.unit+'.'}
  }
  function imageQuality(){const c=q('#cropPreview');if(!c||c.width<2||c.height<2)return{ok:false,severe:true,text:'Qualità immagine: display non selezionato.'};const x=c.getContext('2d',{willReadFrequently:true}),d=x.getImageData(0,0,c.width,c.height).data,w=c.width,h=c.height,gray=new Float32Array(w*h);let sum=0,min=255,max=0,dark=0,light=0;for(let i=0,p=0;i<d.length;i+=4,p++){const v=.299*d[i]+.587*d[i+1]+.114*d[i+2];gray[p]=v;sum+=v;min=Math.min(min,v);max=Math.max(max,v);if(v<18)dark++;if(v>245)light++}let lap=0,n=0;for(let y=1;y<h-1;y+=2)for(let xx=1;xx<w-1;xx+=2){const p=y*w+xx,z=4*gray[p]-gray[p-1]-gray[p+1]-gray[p-w]-gray[p+w];lap+=z*z;n++}const sharp=Math.sqrt(lap/(n||1)),contrast=max-min,px=Math.min(w,h),clipped=Math.max(dark,light)/gray.length;const issues=[];if(px<120)issues.push('ritaglio troppo piccolo');if(sharp<10)issues.push('possibile sfocatura/mosso');if(contrast<45)issues.push('contrasto insufficiente');if(clipped>.72)issues.push('riflesso o esposizione estrema');const severe=px<70||sharp<5||contrast<25;return{ok:!issues.length,severe,sharp:Math.round(sharp),contrast:Math.round(contrast),text:issues.length?'Qualità immagine da verificare: '+issues.join(', ')+'. Nitidezza '+Math.round(sharp)+' · contrasto '+Math.round(contrast)+'.':'Qualità immagine adeguata · nitidezza '+Math.round(sharp)+' · contrasto '+Math.round(contrast)+'.'}}
  function showQuality(){const r=imageQuality();quality.textContent=r.text;quality.className='notice '+(r.ok?'ok':'warning');return r}
  function explainCandidates(){q('#candidateChoices')?.querySelectorAll('.candidate').forEach(b=>{const t=b.textContent||'',m=t.match(/^(.*?) · (\d+)\/6 OCR · (\d+)%$/);if(m){const votes=Number(m[2]),conf=Number(m[3]),level=votes>=4&&conf>=65?'affidabilità alta':votes>=2&&conf>=45?'da verificare':'affidabilità molto bassa';b.textContent=m[1]+' · '+votes+' elaborazion'+(votes===1?'e':'i')+' su 6 · confidenza '+conf+'% · '+level;b.title='Il numero di elaborazioni indica quante varianti OCR hanno prodotto lo stesso valore. La confidenza non è una probabilità calibrata.'}})}
  id.addEventListener('change',applyProfile);reading.addEventListener('change',check);unit.addEventListener('change',check);
  if(analyze){const original=analyze.onclick;analyze.onclick=async function(e){applyProfile();const iq=showQuality();if(iq.severe&&!confirm(iq.text+'\n\nContinuare comunque con l’OCR?')){progress.textContent='Analisi annullata: ripeti la foto o seleziona più precisamente il display.';return}await original?.call(this,e);check();explainCandidates()}}
  const save=q('#saveReading');if(save){const original=save.onclick;save.onclick=function(e){const r=api.validate(reading.value,id.value,unit.value);if(id.value&&r.profile.family!=='unknown'&&!r.ok){alert('Lettura non salvata: '+r.reason+'. Controlla cifre, decimali e unità.');return}return original?.call(this,e)}}
  new MutationObserver(explainCandidates).observe(q('#candidateChoices'),{childList:true,subtree:true});
  document.title='Letture contatori V8.3 TEST';const h=document.querySelector('h1 small');if(h)h.textContent='V8.3 TEST';const foot=q('.foot');if(foot)foot.textContent='V8.3 TEST · controllo qualità immagine e affidabilità OCR esplicita · nessun merge in main.';applyProfile();
})();
